---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: true

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: true
  
  - name: "install node dependencies"
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: latest

  - name: "make new dir"
    shell: |
      if [ -d "~/server" ]
      then
        echo "Directory already exists."
      else
        echo "Creating directory"
        mkdir ~/server
      fi
      exit 0

  - name: "copy artifact"
    copy:
      src: artifact.tar.gz
      dest: ~/server/artifact.tar.gz
    register: copied_files

  - debug: msg="{{ copied_files.stdout }}"

  - name: "Extract backend artifact"
    unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu/server
    register: prints

  - debug: msg="{{ prints.stdout }}"

  - name: "start server"
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start

  # - name: "start server"
  #   shell: pm2 start ~/web/index.js -f
  
